#+title: Doggy Daycare Moc

* This is a MOC

Example Project is for a Doggy Daycare.
Who are the clients? the pets or the people?
Pets are the clients. The have owners.

** BookReservation
[[file:Slices/BookReservation.org]]
[[file:BookReservation.org]]

** Slice Info:
- SliceName: Book Reservation
- Trigger (WFE or UI): User submits Book Reservation UI
- API Verb: POST
- API Endpoint: api/v1/Reservation/Booking
- Command Name: BookReservation
- Command Handler Name: BookReservationHandler
- Event Name: BookedReservation
- ViewName Reservation

- Dev: Sally
- Effort: 5
- Status: RFW

** Story:
As a custoGmer
I want to

** AC:
- G: Previous event or state
- W: User submits Book Reservation UI
- T: BookReservation command will execute the business logic.
- A: BookedReservation event will be saved.
- A: Reservation view will be updated with the relevant event information.


** Diagram

Enter # to complete diagram code+begin_src plantuml :file images/BookedReservation.png
@startuml

rectangle "User submits Book Reservation UI" as trg  #D3D3D3
rectangle "API\nPOST\napi/v1/Reservation/Booking" as api
rectangle "BookReservation\nCommand\Handler" as cmd #add8e6
rectangle "BookedReservation\nEvent" as evt #eedd82
rectangle  "Reservation" as v1 #98fb98

trg -d-> api
api -r-> cmd
cmd -[hidden]r-> v1
cmd -d-> evt
evt .u. v1

@enduml

Enter # to complete diagram code+end_src

** LinkToMOC
Enter # to complete diagram code
Owners book a reservation for a pet.

** BookARoom (this books a specific room for the reservation)
A room (kennel) is booked on behalf of the pet.
[[file:Slices/BookARoom.org][BookARoom]]

** SendConfirmationMessage
A confirmation message is sent to the owner.
[[file:Slices/SendConfirmation.org]]
** CancelReservation
Owner cancels reservation for pet.
[[file:Slices/CancelReservation.org]]

** ReceivePet
Pet Arrives for reservation (Intake process).
[[file:Slices/ReceivePet.org]]
** AddCareInstructions
Add Care-Instructions for reservation.
[[file:Slices/AddCareInstructions.org]]
** AddPersonalityNote
Add Personality-Note for pet.
[[file:Slices/AddPersonalityNote.org]]
** AddCareEvent
Add Care-Event for pet (fed the pet, walked the pet, gave medicine, etc., pet started fight with another guest, pet was attacked by another guest)
[[file:Slices/AddCareEVent.org]]
** AddAltercationEvent
Add Altercation-Event (2 or more pets got into a skirmish).
[[file:Slices/AddAltercation.org]]
